### ISSUE TITLE
[BUG] Unable to delete System from mech

### ISSUE THREAD

**Issue by mindbane** [Eranziel/foundryvtt-lancer#383]
I was unable to delete gear off of several of my player's mechs. Repeatedly refreshing eventually allowed it to happen but appeared random. 

Here are the javascript errors recorded locally
```
foundry.js:23154 Error: The requested texture media/Lans.jpg could not be loaded: Failed to load texture media/Lans.jpg: Server responded with 404
    at TextureLoader._fetchResource (foundry.js:22986:26)
    at async TextureLoader.loadImageTexture (foundry.js:22932:18)
    at async loadTexture (foundry.js:23149:10)
    at async LancerToken.draw (foundry.js:37658:20)
    at async Promise.all (index 3)
    at async TokenLayer.draw (foundry.js:22079:5)
    at async Canvas.draw (foundry.js:19934:11)
   at async Scene.view (foundry.js:17709:7)
    at async Game.initializeCanvas (foundry.js:5657:20)
    at async Game.setupGame (foundry.js:5528:5)
loadTexture @ foundry.js:23154

foundry.js:23154 Error: The requested texture media/Lans.jpg could not be loaded: Failed to load texture media/Lans.jpg: Server responded with 404
    at TextureLoader._fetchResource (foundry.js:22986:26)
    at async TextureLoader.loadImageTexture (foundry.js:22932:18)
    at async loadTexture (foundry.js:23149:10)
    at async LancerToken.draw (foundry.js:37658:20)
    at async Promise.all (index 8)
    at async TokenLayer.draw (foundry.js:22079:5)
    at async Canvas.draw (foundry.js:19934:11)
    at async Scene.view (foundry.js:17709:7)
    at async Game.initializeCanvas (foundry.js:5657:20)
    at async Game.setupGame (foundry.js:5528:5)
loadTexture @ foundry.js:23154

33hooks.js:39 Uncaught TypeError: game.keyboard.getKey is not a function
    at HTMLDocument.<anonymous> (modules/hex-size-support/modules/hooks.js:39:35)`
```

These are the console log errors I saw
```
Error: You may not modify the world.deployable Compendium which is currently locked.
Jan 12 17:43:36 mindbane-fortress node[586]:     at Function._canModify (file:///srv/foundry/foundryvtt/resources/app/dist/database/backend/server-compendium.mjs:1:752)
Jan 12 17:43:36 mindbane-fortress node[586]:     at o.canUserModify (file:///srv/foundry/foundryvtt/resources/app/common/abstract/document.mjs:277:44)
Jan 12 17:43:36 mindbane-fortress node[586]:     at ServerDatabaseBackend._updateDocuments (file:///srv/foundry/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:3005)
Jan 12 17:43:36 mindbane-fortress node[586]:     at async Semaphore._try (file:///srv/foundry/foundryvtt/resources/app/common/utils/semaphore.mjs:99:17)

(node:586) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'upload' of null
Jan 12 17:49:38 mindbane-fortress node[586]:     at FileUploadView.handlePost (file:///srv/foundry/foundryvtt/resources/app/dist/server/views/upload.mjs:1:480)
Jan 12 17:49:38 mindbane-fortress node[586]: (Use `node --trace-warnings ...` to show where the warning was created)
Jan 12 17:49:38 mindbane-fortress node[586]: (node:586) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Jan 12 17:49:38 mindbane-fortress node[586]: (node:586) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

**Comment by Eranziel** [comment]
None of these errors are related to Lancer.

The errors you got in the browser are due to a missing texture, likely because a file was deleted, moved, or renamed.

The third error looks like you tried to modify an item in a locked Compendium. The fourth I'm not sure. Are these two from your server's node process? Systems and modules can't modify the server-side behaviour so there's nothing we can do there.

**Comment by Eranziel** [comment]
Just following up on this. Have you experienced this issue again, and are you able to provide any more details about the circumstances or errors produced? I'll leave the issue open for a while, but without more detail (that indicates the issue lies in the Lancer system) we won't be able to do anything.

(Also, in the future please use one of the issue templates. They help make sure we get relevant information and labels them so we know that they are new and need to be looked at.)
