### ISSUE TITLE
[BUG] Compendium Manager does not render on new worlds

### ISSUE THREAD

**Issue by Eranziel** [Eranziel/foundryvtt-lancer#502]
**Describe the bug**
The Lancer Compendium Manager app fails to open on new worlds created in v10 with Lancer v1.4.0-beta.1

**To Reproduce**
1. Create a new world using v10 and Lancer 1.4.0-beta.1
2. Click on Compendium tab, then Lancer Compendium Manager
3. App fails to render

**Expected behavior**
App should render and allow LCPs to be imported.

**Platform (please complete the following information):**
 - Foundry version 10.291
 - Lancer system version 1.4.0-beta.1

**Additional context**
Console logs the following error:
```
commons.js:4098 Uncaught Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
    at SchemaField._validateType (commons.js:4098:15)
    at SchemaField.validate (commons.js:3824:37)
    at Setting.validate (commons.js:5492:35)
    at new DataModel (commons.js:5269:26)
    at new Document (commons.js:5811:3)
    at new BaseSetting (commons.js:9832:3)
    at new ClientDocumentMixin (foundry.js:13053:5)
    at new Setting (foundry.js:21323:1)
    at ClientSettings.get (foundry.js:2815:21)
    at new LCPManager (lcpManager.ts:77:48)
```

**Comment by Eranziel** [comment]
Can't reproduce. I think this was caused by a bug in the Forge which automatically re-installed custom systems when a new world was created, causing Lancer to revert to 1.2.0.
