### ISSUE TITLE
[BUG] error on build with node v 21

### ISSUE THREAD

**Issue by ImpTs** [Eranziel/foundryvtt-lancer#588]
**Describe the bug**
New error on build introduced in recent update to 2.0-rc

**To Reproduce**
upon running build command, new error appears

**Expected behavior**
Expected normal build behavior

**Screenshots**
https://i.imgur.com/pVSV0wW.png

`[vite:css] Preprocessor dependency "sass" failed to load:
Cannot read properties of undefined (reading 'indexOf')
file: /root/foundryvtt-lancer/src/lancer.scss
error during build:
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at /root/foundryvtt-lancer/node_modules/sass/sass.dart.js:98723:12
    at Object.applyHooksTransformer (/root/foundryvtt-lancer/node_modules/sass/sass.dart.js:1825:14)
    at Object.initHooks (/root/foundryvtt-lancer/node_modules/sass/sass.dart.js:1805:251)
    at Object.initNativeDispatchContinue (/root/foundryvtt-lancer/node_modules/sass/sass.dart.js:1771:9)
    at Object.initNativeDispatch (/root/foundryvtt-lancer/node_modules/sass/sass.dart.js:1765:9)
    at Object.getNativeInterceptor (/root/foundryvtt-lancer/node_modules/sass/sass.dart.js:23908:13)
    at Object.getInterceptor$x (/root/foundryvtt-lancer/node_modules/sass/sass.dart.js:24164:16)
    at Object.set$compile$x (/root/foundryvtt-lancer/node_modules/sass/sass.dart.js:24219:16)
    at Object.main (/root/foundryvtt-lancer/node_modules/sass/sass.dart.js:20842:9)
    at main1 (/root/foundryvtt-lancer/node_modules/sass/sass.dart.js:21561:9)
Error: Preprocessor dependency "sass" failed to load:
Cannot read properties of undefined (reading 'indexOf')
    at loadPreprocessor (file:///root/foundryvtt-lancer/node_modules/vite/dist/node/chunks/dep-df561101.js:39272:29)
    at scss (file:///root/foundryvtt-lancer/node_modules/vite/dist/node/chunks/dep-df561101.js:39310:20)
    at compileCSSPreprocessors (file:///root/foundryvtt-lancer/node_modules/vite/dist/node/chunks/dep-df561101.js:38735:36)
    at compileCSS (file:///root/foundryvtt-lancer/node_modules/vite/dist/node/chunks/dep-df561101.js:38785:42)
    at async Object.transform (file:///root/foundryvtt-lancer/node_modules/vite/dist/node/chunks/dep-df561101.js:38266:56)
    at async transform (file:///root/foundryvtt-lancer/node_modules/rollup/dist/es/shared/node-entry.js:24444:16)
    at async ModuleLoader.addModuleSource (file:///root/foundryvtt-lancer/node_modules/rollup/dist/es/shared/node-entry.js:24644:30)
[15:39:05] 'build' errored after 1.06 s
[15:39:05] Error: exited with error code: 1
    at ChildProcess.onexit (/root/foundryvtt-lancer/node_modules/end-of-stream/index.js:40:36)
    at ChildProcess.emit (node:events:515:28)
    at ChildProcess.emit (node:domain:551:15)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)`

**Platform (please complete the following information):**
2.0-rc dev

**Comment by ImpTs** [comment]
I found the issue here: I was using the newest version of node (21),  which is not currently compatible with Dart programs compiled to JS.
